spring.application.name=AiResumeMatcher

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/resume_matcher?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=0664

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true